version: 0.2

phases:
  install:
    runtime-versions:
       java: openjdk8
  build:
    commands:
      - mvn clean package -DpackageBucket=${PACKAGE_BUCKET}
artifacts:
  files:
    - target/sam/app/packaged-template.yaml
  discard-paths: yes
